spring:
  profiles.active: 

---

spring:
  application:
   name: builder
  datasource:
    url: jdbc:h2:mem:sampletest;MODE=MySQL
    username: root
    password: mypassword
    driverClassName: org.h2.Driver
    hikari:
      idleTimeout: 30000
      connectionTimeout: 180000
      maxLifetime: 1800000
      pool-name: defaultProfileConnectionPool
      auto-commit: false
      
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 7979
  
badges: 
  github: 
    issues: "[![GitHub issues](https://img.shields.io/github/issues/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/issues)" 
    forks: "[![GitHub forks](https://img.shields.io/github/forks/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/network)"
    stars:  "[![GitHub stars](https://img.shields.io/github/stars/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/stargazers)"
    license:  "[![GitHub license](https://img.shields.io/github/license/USERNAME/REPONAME.svg)](https://github.com/USERNAME/REPONAME/blob/master/LICENSE)"
    clone: "git clone git@github.com:USERNAME/REPONAME.git"
  sonar:
    measure: "[![Sonarcloud Status](https://sonarcloud.io/api/project_badges/measure?project=USERNAME_REPONAME&metric=alert_status)](https://sonarcloud.io/dashboard?id=USERNAME_REPONAME)"
  lgtm:
    alerts: "[![Total alerts](https://img.shields.io/lgtm/alerts/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/alerts/)"
    grade: "[![Language grade: Java](https://img.shields.io/lgtm/grade/java/g/USERNAME/REPONAME.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/USERNAME/REPONAME/context:java)"
  travis:
    status: "[![Build Status](https://travis-ci.org/USERNAME/REPONAME.svg?branch=master)](https://travis-ci.org/USERNAME/REPONAME)"
  config:
    placeholder: REPONAME
    githubreposapiurl: "https://api.github.com/users/USERNAME/repos"
---

spring:
  profiles: development
  application:
   name: bp-wallet-server
  datasource:
   url: jdbc:mysql://localhost:3306/sys?useSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   hikari:
    idle-timeout: 1000
    maximum-pool-size: 10
    minimum-idle: 1
    idleTimeout: 3000
    connectionTimeout: 30000
    maxLifetime: 1800000
    pool-name: devProfileConnectionPool
    auto-commit: false
  jpa:
   hibernate.ddl-auto: create
   generate-ddl: true
   show-sql: true
   properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
server:
  port: 8080